{% set version = "1.84-6.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-snowfall
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/snowfall_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/snowfall/snowfall_{{ version }}.tar.gz
  sha256: 2641932b01041e34b7afb1261f649755b4c8d6560080e0e2ee549ffdf3b8b143

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-snow
  run:
    - r-base
    - r-snow

test:
  commands:
    - $R -e "library('snowfall')"           # [not win]
    - "\"%R%\" -e \"library('snowfall')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=snowfall
  license: GPL-2.0-or-later
  summary: Usability wrapper around snow for easier development of parallel R programs. This package offers e.g. extended error checks, and additional functions. All functions work in sequential mode, too, if no cluster is present or wished. Package is also designed as connector to the cluster management tool sfCluster,
    but can also used without it.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
