travis:
  secure:
    BINSTAR_TOKEN: H4D6e/j18xh29KVPRP7/kM8R4EZSaP00VX1+OdxveydQYX+Z1jHuea6I3Gulr/c+++xDcszHtSKe39wu+j3uj8YiSzFCwOKtw+nMxVDAZOIWN3JSiQAaFgZUkyk+AlgeWByQ0xPzCrZIjJyexi9rPPRUwYyWgdnzKV2ZzccXrArBLoK8T1/QpvnJ8WNNO/BCAn3SdJJ1iSBLt504+zkBEFfZ1uT1VYp5uiy5QKQz3fBPoU3zdlQzBzcomUZ05Zsgd4IY2IvZOvZ/URDgJ0UNTx6i/yH8C+f3anG2Jg1+No9XntyzF9IrVCBiroi4bdALykwHGHjCy7o/C/e9uTId0frPD4nFFRqDQmR3nQRCNpxQJTWI3yQyPUtN4+Ni8pPX3cR1051PVHyntXaqeokq2K/Ipau58vVgPOo9cz7Dl5pdH6aFrxiKY4253yo47xBjfVS6Nb+0TGCGiyQ9WcX99l8fiIPGU12WyB34rq74cd7cCqCHJXgEypfK25fhzVgaaonFk49E8Mv3dRu/4LpstNX2Rtu8w1wKfNizCUTg/Cy7cHJJML013f8iGtT6zpP/1JzFPC+ThcGbN8IDlRSUJIku0bzT5UnlggC2p4Ah9IfhKOhDQLRlkiJ7SuU0YzdslzW6nP4Ph14dbdHi2gWHV+U9fWzu2dxcrrSe/esWnRo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
